apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test01-nginx-ingress
  namespace: test01
spec:
  ingressClassName: nginx
  rules:
  - host: hello.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: test01-nginx-service
              port:
                number: 80
