apiVersion: v1
kind: Service
metadata:
  name: test01-nginx-service
  namespace: test01
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: hellonginx